- name: ping
  hosts: web
  tasks: 
  - name: ping the server
    ansible.builtin.ping:


# running the playbook
# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 01-playbook.yaml 