- name: installing and running NGINX
  hosts: [web]
  become: yes    # -b   giving sudo access
  tasks: 
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: starting the nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


# running the playbook
# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 03-nginx.yaml 