- name: variables from files
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
        



# running the playbook
# ansible-playbook -i inventory.ini 