- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: please enter course name # this is the promot- means it read the data from user. it stores the data in the COURSE variable
    - name: DURATION
      prompt: please enter duration 
    - name: TRAINER
      prompt: please enter trainer name
  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"


# running the playbook
# ansible-playbook -i inventory.ini 