- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables
    GREET: "PLAY"
  vars_files:
  - course.yaml
  # vars_prompt:
  #   - name: GREET
  #     prompt: Enter the values
  #     private: false
    
  tasks: 
  - name: print the variable
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"


# running the playbook
#1. ansible-playbook -i inventory.ini 12-preference.yaml -e "GREET=ARGS"
#1. first preference goes to command line variables(args)

#2.ansible-playbook -i inventory.ini 12-preference.yaml 
#2. second preference goes to TASK level variables

#3. ansible-playbook -i inventory.ini 12-preference.yaml
#3. third preference goes to prompt

