- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables
    GREET: "PLAY"
  vars_files:
    - course.yaml
  vars_prompt:
    - name: GREET
      prompt: Enter the values
      private: false
    
  tasks: 
  - name: print the variable
    vars:
      GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"


# running the playbook
#1. ansible-playbook -i inventory.ini 12-vars-preference.yaml -e "GREET=ARGS"
#1. first preference goes to command line variables(args)

#2.ansible-playbook -i inventory.ini 12-vars-preference.yaml 
#2. second preference goes to TASK level variables

#3. ansible-playbook -i inventory.ini 12-vars-preference.yaml
#3. sixth preference goes to variables from files

#4. ansible-playbook -i inventory.ini 12-vars-preference.yaml
#4. third preference goes to prompt


#5. ansible-playbook -i inventory.ini 12-vars-preference.yaml 
#5. fourth preference goes to Play variables

#6. ansible-playbook -i inventory.ini 12-vars-preference.yaml
#6. fifth preference goes to INVENTORY variables




