- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Remesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange "  # string
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs"
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"
  
  - name: convert list into map
    vars:
      course:
        - {'key': 'name', 'value': 'ansible'} 
        - {'key': 'duration', 'value': '10hrs"'}
        - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"




# output

# TASK [handle undefined variable] *************************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "Hello Remesh"
# }

# TASK [convert string to list] ****************************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "Fruits are: ['apple', ' banana', ' orange ']"
# }

